# Site
darkmode: true
repository: the-shoemaker/cv
favicon: images/favicon.ico

# Personal info
name: Dan Schumacher
title: Aspiring Web Developer
email: s.dan.jonas@gmail.com
# website: www.the-shoemaker.ch

# Social links
# twitter_username: jekyll
github_username: the-shoemaker
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: DanTheImageMan
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Dan Schumacher.

  I currently attend my last year of secondary school and I am eager to
  get started with my professional life.

  Over the last couple of years my interest in technology has grown. It started
  with small DIY soldering projects, which quickly lead to using my computer
  for more than just surfing the web.

  After my first steps with [Scratch](https://scratch.mit.edu/) I taught myself
  rudimentary programming skills, mostly in Python.

  I quickly realized that programming was more than a hobby to me. I want to do
  this professionally.
# Projects Section
projects_title: Hobbies

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: When I'm Not Programming
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
